require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HospedesController do

  # This should return the minimal set of attributes required to create a valid
  # Hospede. As you add validations to Hospede, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "cpf" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HospedesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hospedes as @hospedes" do
      hospede = Hospede.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hospedes).should eq([hospede])
    end
  end

  describe "GET show" do
    it "assigns the requested hospede as @hospede" do
      hospede = Hospede.create! valid_attributes
      get :show, {:id => hospede.to_param}, valid_session
      assigns(:hospede).should eq(hospede)
    end
  end

  describe "GET new" do
    it "assigns a new hospede as @hospede" do
      get :new, {}, valid_session
      assigns(:hospede).should be_a_new(Hospede)
    end
  end

  describe "GET edit" do
    it "assigns the requested hospede as @hospede" do
      hospede = Hospede.create! valid_attributes
      get :edit, {:id => hospede.to_param}, valid_session
      assigns(:hospede).should eq(hospede)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hospede" do
        expect {
          post :create, {:hospede => valid_attributes}, valid_session
        }.to change(Hospede, :count).by(1)
      end

      it "assigns a newly created hospede as @hospede" do
        post :create, {:hospede => valid_attributes}, valid_session
        assigns(:hospede).should be_a(Hospede)
        assigns(:hospede).should be_persisted
      end

      it "redirects to the created hospede" do
        post :create, {:hospede => valid_attributes}, valid_session
        response.should redirect_to(Hospede.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hospede as @hospede" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospede.any_instance.stub(:save).and_return(false)
        post :create, {:hospede => { "cpf" => "invalid value" }}, valid_session
        assigns(:hospede).should be_a_new(Hospede)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospede.any_instance.stub(:save).and_return(false)
        post :create, {:hospede => { "cpf" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hospede" do
        hospede = Hospede.create! valid_attributes
        # Assuming there are no other hospedes in the database, this
        # specifies that the Hospede created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hospede.any_instance.should_receive(:update).with({ "cpf" => "1" })
        put :update, {:id => hospede.to_param, :hospede => { "cpf" => "1" }}, valid_session
      end

      it "assigns the requested hospede as @hospede" do
        hospede = Hospede.create! valid_attributes
        put :update, {:id => hospede.to_param, :hospede => valid_attributes}, valid_session
        assigns(:hospede).should eq(hospede)
      end

      it "redirects to the hospede" do
        hospede = Hospede.create! valid_attributes
        put :update, {:id => hospede.to_param, :hospede => valid_attributes}, valid_session
        response.should redirect_to(hospede)
      end
    end

    describe "with invalid params" do
      it "assigns the hospede as @hospede" do
        hospede = Hospede.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospede.any_instance.stub(:save).and_return(false)
        put :update, {:id => hospede.to_param, :hospede => { "cpf" => "invalid value" }}, valid_session
        assigns(:hospede).should eq(hospede)
      end

      it "re-renders the 'edit' template" do
        hospede = Hospede.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospede.any_instance.stub(:save).and_return(false)
        put :update, {:id => hospede.to_param, :hospede => { "cpf" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hospede" do
      hospede = Hospede.create! valid_attributes
      expect {
        delete :destroy, {:id => hospede.to_param}, valid_session
      }.to change(Hospede, :count).by(-1)
    end

    it "redirects to the hospedes list" do
      hospede = Hospede.create! valid_attributes
      delete :destroy, {:id => hospede.to_param}, valid_session
      response.should redirect_to(hospedes_url)
    end
  end

end
